update buckyos real gateway config tests

diff --git a/tests/buckyos/boot_gateway.yaml b/tests/buckyos/boot_gateway.yaml
--- a/tests/buckyos/boot_gateway.yaml
+++ b/tests/buckyos/boot_gateway.yaml
@@ -1,148 +1,193 @@
 collections:
   APP_INFO:
     type: json_map
-    file_path: ./app_info.json
+    file_path: ./node_gateway_info.json#app_info
     only_read_file: true
   SERVICE_INFO:
     type: json_map
-    file_path: ./service_info.json
+    file_path: ./node_gateway_info.json#service_info
     only_read_file: true
   NODE_ROUTE_MAP:
     type: json_map
-    file_path: ./node_route_map.json
+    file_path: ./node_gateway_info.json#node_route_map
+    only_read_file: true
+  TRUST_KEY:
+    type: json_map
+    file_path: ./node_gateway_info.json#trust_key
     only_read_file: true
 
 stacks:
   node_rtcp:
-    id: node_rtcp
     protocol: rtcp
     bind: 0.0.0.0:2980
     key_path: ./node_private_key.pem
     device_config_path: ./node_device_config.json
-    hook_point:
-      main:
-        id: main
-        priority: 1
-        blocks:
-          default:
-            id: default
-            priority: 1
-            block: |
-              return "forward ${REQ.protocol}:///${REQ.dest_host}:${REQ.dest_port}";
+    # 基于RTCP（包括中转)的身份验证
+    # 1） new_http_stream的时候，可以把来源did写入到REQ中供后续使用，但rtcp中转后，只能看到中转节点的did(可以简单的要求中转节点)
+    # 2） new_rtcp_stream的时候，是中转，默认只允许zone内中转(来源必须是zone内的设备)
+
               
   zone_gateway_http:
-    id: zone_gateway_http
     protocol: tcp
     bind: 0.0.0.0:80
     hook_point:
       main:
         priority: 1
         blocks:
-          main:
+          default:
             priority: 1
             block: |
-              global CONTROL_PANEL_URL="https://sys.test.buckyos.io/";
+              return "server node_gateway";
+
+  #zone_gateway tls stack is automatically generated by scheduler and write to node_gateway.json
+
+  node_gateway_http:
+    protocol: tcp
+    bind: 127.0.0.1:3180
+    hook_point:
+      main:
+        priority: 1
+        blocks:
+          default:
+            priority: 1
+            block: |
+              return "server node_gateway";
+
+servers:
+  node_gateway:
+    type: http
+    gzip_vary: true
+    gzip_types:
+      - text/html
+      - text/css
+      - application/javascript
+      - application/json
+      - application/xml    
+
+    hook_point:
+      main:
+        blocks:
+          default:
+            priority: 1
+            block: |
+
               global THIS_NODE_ID="ood1";
-              exec zone_http_selector:get_service_info_from_req;
-              exec zone_http_selector:get_app_infp_from_req;
-              echo "APP_ID: ${APP_ID}";
-              echo "SERVICE_ID: ${SERVICE_ID}";
-
+              global THIS_ZONE_HOST="test.buckyos.io";
+              global CONTROL_PANEL_URL="https://sys.${THIS_ZONE_HOST}/";
+              exec get_app_info_from_req;
+              exec get_service_info_from_req;
               if !eq $SERVICE_ID "" then
-                exec zone_http_selector:permit_check || echo "permit check failed" && reject;
-                exit $(exec zone_http_selector:forward_to_service);
+                echo "access service";
+                exec permit_check || echo "access service permit check failed" && reject;
+                return --from chain $(exec forward_to_service);
               elif !eq $APP_ID "" then
-                exec zone_http_selector:check_oauth || echo "oauth check skipped";
-                exit $(exec zone_http_selector:forward_to_app);
+                echo "access app";
+                if eq $(exec check_oauth) true then
+                  return --from chain $(exec forward_to_app);
+                else
+                  echo "oauth failed";
+                  local oauth_login_url=$(append "${CONTROL_PANEL_URL}/oauth/login?redirect_url=" $(url_encode $REQ.url));
+                  redirect $oauth_login_url;
+                end
               end
-
+              echo "reject";
               reject;
 
 
 
-global_process_chains:
-  zone_http_selector:
-    priority: 1
-    blocks:
-      default:
-        priority: 1
-        block: |
-          echo "unreachable";
-          reject;
-
-      check_block_list:
-        # 通过请求信息判断是否允许访问本zone
-        priority: 110
-        block: |
-          echo "check_block_list block";     
-      
-      get_app_infp_from_req: 
-        # 尝试通过域名解析得到appid
-        # 找到会设置APP_ID和TARGET_APP_INFO
-        priority: 120
-        
-        # 匹配REQ.host,app_info_map, 返回appid, 匹配模式是 appprefix.*, appprefix-*.*
-        block: |
-          map-create hp;
-          match-reg --capture hp $REQ.host "^([a-zA-Z0-9_]+)[-.]" || return false;
-          match-include $APP_INFO $hp[1] || return false;
-          global TARGET_APP_INFO=$APP_INFO[$hp[1]];
-          global APP_ID=$TARGET_APP_INFO.appid;
-          return $APP_ID;
-
-      get_service_info_from_req:
-          # 尝试通过匹配REQ.path 得到 service_id,/kapi/$service_id 或 /kapi/$service_id/*
-          # 找到会设置SERVICE_ID和TARGET_SERVICE_INFO
-          priority: 130
-          block: |
-            map-create hp;
-            match-reg --capture hp $REQ.path "^/kapi/([a-zA-Z0-9_-]+)(/.*)?" || return false;
-            match-include $SERVICE_INFO $hp[1] || return false;
-            global TARGET_SERVICE_INFO=$SERVICE_INFO[$hp[1]];
-            global SERVICE_ID=$hp[1];
-            return $hp[1];
+          get_app_info_from_req:
+            # 尝试通过域名解析得到appid
+            # 找到会设置APP_ID和TARGET_APP_INFO
+            # host 必须精确匹配 app_id.${THIS_ZONE_HOST} 或 app_id-${THIS_ZONE_HOST} 格式
+            priority: 120
+            block: |
+              map-create hp;
+              if $REQ.host == $THIS_ZONE_HOST then
+                map-add hp 1 "_";
+              else
+                match-reg --capture hp $REQ.host "^([a-zA-Z0-9_]+)[-.]" || return false;
+              end
+              match-include $APP_INFO $hp[1] || return false;
+              local app_info=$APP_INFO[$hp[1]];
+              if match-include $app_info "service_id" then
+                #echo "app_info is a service ${app_info.service_id}";
+                global SERVICE_ID=$app_info.service_id;
+                global TARGET_SERVICE_INFO=$app_info;
+              else
+                #echo "app_info is an app ${app_info.app_id}";
+                global APP_ID=$app_info.app_id;
+                global TARGET_APP_INFO=$app_info;
+              end
+              return true;
 
 
-      check_oauth:
-        # 判断是否需要在网关做OAuth2.0认证
-        # 如果app的sdk_version>=10，表示app自己处理认证，网关不需要介入
-        priority: 135
-        block: |
-          echo "check_oauth block for app ${APP_ID}";
-          eq $TARGET_APP_INFO.sdk_version "0" || return true;
-          local cookies=$(parse-cookie $REQ.Cookie);
-          local oauth_login_url=$(append "${CONTROL_PANEL_URL}/oauth/login?redirect_url=" $(url_encode $REQ.url));
-          eq $cookies.session_token "" && redirect $oauth_login_url;
-          #local payload=$(verify-jwt $cookies.session_token $TRUST_KEY);
-          #eq $payload false && redirect $oauth_login_url;
-          #eq $payload.appid $APP_ID || redirect $oauth_login_url;
-          return true;
+          get_service_info_from_req:
+            # 尝试通过匹配REQ.path 得到 service_id,/kapi/$service_id 或 /kapi/$service_id/*
+            # 找到会设置SERVICE_ID和TARGET_SERVICE_INFO
+            priority: 130
+            block: |
+              map-create hp;
+              match-reg --capture hp $REQ.path "^/kapi/([a-zA-Z0-9_-]+)(/.*)?" || return false;
+              match-include $SERVICE_INFO $hp[1] || return false;
+              global TARGET_SERVICE_INFO=$SERVICE_INFO[$hp[1]];
+              global SERVICE_ID=$hp[1];
+              return $hp[1];
 
-      permit_check: 
-        # 判断 来源 是否有访问权限
-        # 判断 应用是否有权限访问service
-        priority: 140
-        block: |
-          eq $APP_ID "" && return true;
-          match-include $TARGET_APP_INFO.block_services $SERVICE_ID && return false;
-          return true;
+          check_oauth:
+            # 判断是否需要在网关做OAuth2.0认证
+            # 如果app的sdk_version>=10，表示app自己处理认证，网关不需要介入
+            priority: 135
+            block: |
+              eq $TARGET_APP_INFO.access_mode "public" && return true;
+              local cookies=$(parse-cookie $REQ.Cookie);
+              match-include $cookies "buckyos_session_token" || error false;
 
+              capture --value payload --error jwt_error $(verify-jwt $cookies.buckyos_session_token $TRUST_KEY);
+              eq $jwt_error false || error false;
+              eq $payload.appid $APP_ID || error false;
+              return true;
 
-      forward_to_service:
-          priority: 150
-          block: |
-            echo "forward_to_service block";
-            if eq $TARGET_SERVICE_INFO.selector $THIS_NODE_ID then
-              local port=$SERVICE_INFO.selector[$THIS_NODE_ID].port;
-              forward "http://127.0.0.1:${port}";
-            else
-              forward round_robin --map $TARGET_SERVICE_INFO.selector;
-            end
+          permit_check:
+            # 判断 来源 是否有访问权限
+            # 判断 应用是否有权限访问service
+            priority: 140
+            block: |
+              eq $APP_ID "" && return true;
+              match-include $TARGET_APP_INFO.block_services $SERVICE_ID && error false;
+              return true;
 
-      forward_to_app:
-          id: forward_to_app
-          priority: 160
-          block: |
-            echo "forward_to_app block";
-            eq $TARGET_APP_INFO.nodeid $THIS_NODE_ID && forward "http://127.0.0.1:${TARGET_APP_INFO.port}";
-            forward "${NODE_ROUTE_MAP[$TARGET_APP_INFO.nodeid]}:${TARGET_APP_INFO.port}";
+          forward_to_service:
+            priority: 150
+            block: |
+              if match-include $TARGET_SERVICE_INFO.selector $THIS_NODE_ID then
+                local port=$TARGET_SERVICE_INFO.selector[$THIS_NODE_ID].port;
+                forward "http://127.0.0.1:${port}";
+              else
+                map-create target_node_map;
+                for node_id, node_info in $TARGET_SERVICE_INFO.selector then
+                    local target_rtcp_url = ${NODE_ROUTE_MAP[$node_id]}
+                    if !eq target_rtcp_url "" then
+                      local target_rtcp_url_with_port = "${target_rtcp_url}:${node_info.port}";
+                      echo "target_rtcp_url_with_port: ${target_rtcp_url_with_port}";
+                      map-add target_node_map $target_rtcp_url_with_port $node_info.weight;
+                    end
+                end
+                forward round_robin --map $target_node_map;
+              end
+              echo "forward to service failed";
+              reject;
+
+          forward_to_app:
+            priority: 160
+            block: |
+              echo "forward_to_app block";
+              eq $TARGET_APP_INFO.node_id $THIS_NODE_ID && forward "http://127.0.0.1:${TARGET_APP_INFO.port}";
+              forward "${NODE_ROUTE_MAP[$TARGET_APP_INFO.nodeid]}:${TARGET_APP_INFO.port}";
+
+          check_block_list:
+            # 通过请求信息判断是否允许访问本zone
+            priority: 110
+            block: |
+              return true;
+
+    
